export const APP_TEXTS = {
  LABELS: {
    USERNAME: "Username",
    PASSWORD: "Password",
    EMAIL: "Email",
    START_DATE: "Start Date",
    END_DATE: "End Date",
    PRICE: "Price",
    SIZE: "Size",
    STOP_PRICE: "Stop Price",
    STOP_LOSS: "Stop Loss",
    TAKE_PROFIT: "Take Profit",
    CALLBACK_RATE: "Callback Rate",
    ACTIVATION_PRICE: "Activation Price",
    TOTAL_SIZE: "Total Size",
    TOTAL_TIME: "Total Time",
    LOWER_PRICE: "Lower Price",
    HIGHER_PRICE: "Higher Price",
    ORDER_COUNT: "Order Count",
  },
  ACTIONS: {
    BUY: "Buy",
    SELL: "Sell",
    SUBMIT: "Submit",
    CANCEL: "Cancel",
    SAVE: "Save",
    DELETE: "Delete",
    EDIT: "Edit",
  },
  STATUS: {
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    PENDING: "Pending",
    APPROVED: "Approved",
    REJECTED: "Rejected",
  },
  ERRORS: {
    REQUIRED: "",
    INVALID_EMAIL: "",
    MIN_LENGTH: "",
    MAX_LENGTH: "",
  },
};
